#include "cba2.h"

void build() {
    BuildInfo buildInfo;
    
    // Try to read existing build file
    FILE* fp = fopen("cba.build", "r");
    
    if(fp == NULL) {
        printf("No build file found. Auto-detecting project...\n");
        detectProject(&buildInfo);
        generateBuildFile(&buildInfo);
        fp = fopen("cba.build", "r");
        if(fp == NULL) {
            printf("Error: Could not create build file.\n");
            return;
        }
    }
    
    // Parse and build
    BuildParser(fp, &buildInfo);
    fclose(fp);
    generateCMake(&buildInfo);
    runCMake();
}

void detectProject(BuildInfo* buildInfo) {
    // Set intelligent defaults
    strcpy(buildInfo->version, "1.0.0");
    strcpy(buildInfo->cmakeMinVersion, "3.10");
    strcpy(buildInfo->ninjaMinVersion, "1.10");
    
    // Guess project name from directory
    char cwd[1024];
    getcwd(cwd, 1024);
    char* lastSlash = strrchr(cwd, PATH_SEPARATOR);
    if(lastSlash) {
        strcpy(buildInfo->name, lastSlash + 1);
    } else {
        strcpy(buildInfo->name, "myproject");
    }
    
    // Guess output type (executable if main.c exists, else library)
    FILE* test = fopen("main.c", "r");
    if(test) {
        strcpy(buildInfo->output, "executable");
        fclose(test);
    } else {
        strcpy(buildInfo->output, "library");
    }
}

void generateBuildFile(BuildInfo* buildInfo) {
    FILE* fp = fopen("cba.build", "w");
    if(!fp) return;
    
    fprintf(fp, "# Auto-generated by cba init\n");
    fprintf(fp, "name=%s\n", buildInfo->name);
    fprintf(fp, "version=%s\n", buildInfo->version);
    fprintf(fp, "cmakeMinVersion=%s\n", buildInfo->cmakeMinVersion);
    fprintf(fp, "ninjaMinVersion=%s\n", buildInfo->ninjaMinVersion);
    fprintf(fp, "output=%s\n", buildInfo->output);
    
    fclose(fp);
    printf("Created cba.build with auto-detected settings\n");
}

void generateCMake(BuildInfo* buildInfo) {
    FILE* fp = fopen("CMakeLists.txt", "w");
    if(!fp) {
        printf("Error: Could not create CMakeLists.txt\n");
        return;
    }
    
    // Header
    fprintf(fp, "cmake_minimum_required(VERSION %s)\n", buildInfo->cmakeMinVersion);
    fprintf(fp, "project(%s VERSION %s)\n", buildInfo->name, buildInfo->version);
    fprintf(fp, "set(CMAKE_C_STANDARD 11)\n");
    fprintf(fp, "set(CMAKE_C_STANDARD_REQUIRED True)\n\n");
    
    // Find all source files
    fprintf(fp, "file(GLOB_RECURSE SOURCES \"*.c\")\n");
    fprintf(fp, "file(GLOB_RECURSE HEADERS \"*.h\")\n\n");
    
    // Create target based on output type
    if(strcmp(buildInfo->output, "executable") == 0) {
        fprintf(fp, "add_executable(${PROJECT_NAME} ${SOURCES} ${HEADERS})\n");
    } else {
        fprintf(fp, "add_library(${PROJECT_NAME} ${SOURCES} ${HEADERS})\n");
    }
    
    // Add subdirectories automatically
    char* directories = getListedDirectories(".");
    if(directories) {
        char* dir = strtok(directories, "\n");
        while(dir) {
            // Skip common build/system directories
            if(shouldIncludeDirectory(dir)) {
                fprintf(fp, "add_subdirectory(%s)\n", dir);
            }
            dir = strtok(NULL, "\n");
        }
        free(directories);
    }
    
    fclose(fp);
    printf("Generated CMakeLists.txt\n");
}

int shouldIncludeDirectory(const char* dir) {
    const char* skipDirs[] = {
        "build", ".git", ".vscode", ".github", ".idea",
        "configs", "docs", "tests", "bin", "obj", NULL
    };
    
    for(int i = 0; skipDirs[i]; i++) {
        if(strcmp(dir, skipDirs[i]) == 0) return 0;
    }
    return 1;
}

void runCMake() {
    printf("Running CMake...\n");
    
    // Check if CMake exists
    if(system("cmake --version > nul 2>&1") != 0) {
        printf("Error: CMake not found. Please install CMake.\n");
        return;
    }
    
    // Create build directory if it doesn't exist
    system("if not exist build mkdir build");
    
    // Run CMake
    int result = system("cd build && cmake .. -G Ninja");
    
    if(result == 0) {
        printf("\n✓ Build files generated successfully!\n");
        printf("  Run 'cba build' again to compile, or:\n");
        printf("  cd build && ninja\n");
    } else {
        printf("\n✗ CMake configuration failed.\n");
    }
}

void init() {
    BuildInfo buildInfo;
    detectProject(&buildInfo);
    generateBuildFile(&buildInfo);
    printf("\nProject initialized! Run 'cba build' to generate files.\n");
}

void BuildParser(FILE* file, BuildInfo* buildInfo) {
    char line[256];
    rewind(file); // Make sure we're at start
    
    while(fgets(line, sizeof(line), file)) {
        line[strcspn(line, "\n")] = 0;
        if(line[0] == '\0' || line[0] == '#') continue;
        
        char* key = line;
        char* value = strchr(line, '=');
        if(!value) continue;
        
        *value = '\0';
        value++;
        
        key = trimWhitespace(key);
        value = trimWhitespace(value);
        
        if(strcmp(key, "version") == 0)
            strcpy(buildInfo->version, value);
        else if(strcmp(key, "name") == 0)
            strcpy(buildInfo->name, value);
        else if(strcmp(key, "cmakeMinVersion") == 0)
            strcpy(buildInfo->cmakeMinVersion, value);
        else if(strcmp(key, "ninjaMinVersion") == 0)
            strcpy(buildInfo->ninjaMinVersion, value);
        else if(strcmp(key, "output") == 0)
            strcpy(buildInfo->output, value);
    }
}

void clean() {
    system("rd /s /q build 2> nul");
    printf("Cleaned build directory\n");
}